### ISSUE TITLE
can't find docker image

### ISSUE THREAD

**Issue by PeerHerholz** [miykael/nipype_course#1]
Hey,

I just tried to run the docker image on my mac (El Capitan). 
My docker installation works fine, but when I run:

`docker run -ti --rm -p 8888:8888 miykael/nipype_course`

I get the following error: 

```
Unable to find image 'miykael/nipype_course:latest' locally
docker: Error response from daemon: manifest for miykael/nipype_course:latest not found.
```

When I use: 

`docker search miykael`

the output looks as follows: 

```
NAME                    DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
miykael/nipype_level3   Neuroimaging environment with Nipype, FSL,...   0                    [OK]
miykael/nipype_level2   Neuroimaging environment with Nipype, FSL,...   0                    [OK]
miykael/nipype_level1   Neuroimaging environment with Nipype, FSL ...   0                    [OK]
miykael/nipype_level0   Nipype environment with dipy, matplotlib, ...   0                    [OK]
miykael/nipype_level4   Neuroimaging environment with Nipype, FSL,...   0                    [OK]
miykael/nipype_level5   Neuroimaging environment with Nipype, FSL,...   0                    [OK]

```

Am I missing something (maybe mac related) here, or is the docker image really not available?

**Comment by miykael** [comment]
Hi @PeerHerholz, sorry, I did some major changes (i.e. I needed to reset the repo because it was already 9GB big). I've just finished, and upload right now the new image. Internally the image is exactly the same, but now it downloads the ds102 example data directly from openfmri.org and the notebooks from https://github.com/miykael/nipype_tutorial.

So, if you check again in about 1h, everything should be back where it belongs. For the time being, you can now check out all tutorial notebooks directly online (https://miykael.github.io/nipype_tutorial/) without the need of any docker image. Well, except if you want to have it interactive of course :-)

**Comment by PeerHerholz** [comment]
Hi @miykael,

I just tried it again and everything worked fine. 
The download took about 20 min over a standard wifi. 
It also seems that the rest (e.g. all notebooks, etc.) works fine too. 
So, I guess, you can include the hint that it works like in ubuntu within the "Mac" section, as I used the same commands.
